# IMPORTANTE: Este é um TEMPLATE!
# 1. Crie a pasta .streamlit no seu projeto
# 2. Copie este arquivo para .streamlit/secrets.toml
# 3. Preencha com suas credenciais reais
# 4. NUNCA commite este arquivo no Git!

[auth]
# Credenciais principais
username = "gxbriellops"
password = "aeiou8734"

# Credenciais demo (opcional)
demo_username = "gxbriellops"
demo_password = "aeiou8734"

[api_keys]
# Suas chaves de API
GEMINI_API_KEY = "AIzaSyAWx9pZRWzlShzqF7-CiEwEPf3TE6HqzMc"
GROQ_API_KEY = "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"

[database]
# Para SQLite (padrão)
SQLITE_PATH = "./data/gastos_receita.db"

# Para PostgreSQL (opcional - descomente se usar)
# DATABASE_URL = "postgresql://user:password@host:port/database"

# Exemplo Render PostgreSQL:
# DATABASE_URL = "postgresql://economiza_user:sua_senha@dpg-xxxxx.render.com/economiza_db"

# Exemplo Supabase:
# DATABASE_URL = "postgresql://postgres:sua_senha@db.xxxxx.supabase.co:5432/postgres"